<?php

/**
 * @file
 * Installs lmi3d metadata on the behalf of modules at time of install.
 */

/**
 * Implements hook_modules_installed().
 */
function lmi3d_metadata_modules_installed($modules) {
  // @todo Move this to an event once we have HookEvent.
  foreach ($modules as $module) {
    if (!\Drupal::isConfigSyncing()) {
      \Drupal::service('lmi3d_metadata.manager')->importContent($module);
    }
  }
}
